name: fluid_logger
description: Clutterless logger capable of displaying times, positions in file.
version: 0.0.2
homepage: https://github.com/adriank/fluid_logger

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
