name: fluid_logger
description: Clutterless logger capable of displaying times, positions in file.
version: 0.0.6
homepage: https://github.com/adriank/fluid_logger

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:

dev_dependencies:
  test: ^1.25.7
